let wwf_animals = [
{name: "African Elephant", scientific: "Loxodonta africana", status: "Vulnerable"},
{name: "African Wild Dog", scientific: "Lycaon pictus", status: "Endangered"},
{name: "Albacore Tuna", scientific: "Thunnus alalunga", status: "Near Threatened"},
{name: "Amazon River Dolphin", scientific: "Scientific Name Inia geoffrensis", status: ""},
{name: "Amur Leopard", scientific: "Panthera pardus orientalis", status: "Critically Endangered"},
{name: "Amur Tiger", scientific: "Panthera tigris altaica", status: "Endangered"},
{name: "Arctic Fox", scientific: "Vulpes lagopus", status: "Least Concern"},
{name: "Arctic Wolf", scientific: "Canis lupus arctos", status: "Least Concern"},
{name: "Asian Elephant", scientific: "Elephas maximus indicus", status: "Endangered"},
{name: "Beluga", scientific: "Delphinapterus leucas", status: "Near Threatened"},
{name: "Bengal Tiger", scientific: "Panthera tigris tigris", status: "Endangered"},
{name: "Bigeye Tuna", scientific: "Thunnus obesus", status: "Vulnerable"},
{name: "Black Rhino", scientific: "Diceros bicornis", status: "Critically Endangered"},
{name: "Black Spider Monkey", scientific: "Ateles paniscus", status: "Vulnerable"},
{name: "Black-footed Ferret", scientific: "Mustela nigripes", status: "Endangered"},
{name: "Blue Whale", scientific: "Balaenoptera musculus", status: "Endangered"},
{name: "Bluefin Tuna", scientific: "Thunnus Thynnus", status: "Endangered"},
{name: "Bonobo", scientific: "Pan paniscus", status: "Endangered"},
{name: "Bornean Orangutan", scientific: "Pongo pygmaeus", status: "Critically Endangered"},
{name: "Borneo Pygmy Elephant", scientific: "Elephas maximus borneensis", status: "Endangered"},
{name: "Bowhead Whale", scientific: "Balaena mysticetus", status: "Least Concern"},
{name: "Brown Bear", scientific: "Ursus arctos", status: "Least Concern"},
{name: "Chimpanzee", scientific: "Pan troglodytes", status: "Endangered"},
{name: "Common Bottlenose Dolphin", scientific: "Tursiops truncates", status: "Least Concern"},
{name: "Cross River Gorilla", scientific: "Gorilla gorilla diehli", status: "Critically Endangered"},
{name: "Dolphins and Porpoises", scientific: "", status: ""},
{name: "Dugong", scientific: "Dugong dugon", status: "Vulnerable"},
{name: "Eastern Lowland Gorilla", scientific: "Gorilla beringei graueri", status: "Critically Endangered"},
{name: "Elephant", scientific: "", status: ""},
{name: "Fin Whale", scientific: "Balaenoptera physalus", status: "Endangered"},
{name: "Forest Elephant", scientific: "", status: "Vulnerable"},
{name: "Galápagos Penguin", scientific: "Spheniscus mendiculus", status: "Endangered"},
